# Title of your website
title: 'Junta de Vecinos Reñaca Costa'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'A Flexible Theme for Jekyll'

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: 'Reñaca Costa. Distrito 105'

# The credits show up in the includes/_footer.html – It would be nice of you to leave a link to Phlow or Feeling Responsive as a thank you :)
credits: '<p>Creado con &hearts; a base de <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a>.</p>'

# Main author of the website
# See > authors.yml
author: Giovanna

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: ''
baseurl: ''

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: 

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: '/images/'


# Logo size is 600x80 pixels
logo: "logo.png"

# Plugins
plugins:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate


paginate: 5                      # Paginates all X entries
paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work


# Theme works best with Kramdown (using the table of contents function)
markdown           : kramdown
permalink          : /:categories/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - vendor
    - excluded

# The language setting is used in /includes/header.html for html-settings
language: 'es'

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

collections:
  trabajo:
    output: true
    permalink: /:collection/:path/

# Default Settings

defaults:
  - scope:
      path: ""
      type: trabajo
    values:
      layout: trabajo
  - scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: giovanna     # Default author for pages
  - scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: giovanna     # Default author for posts

#  Open _data/navigation.yml to adjust the left and right topbar navigation

google_site_verification        : 'Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ'
bing_webmastertools_id          : '0FB4C028ABCF07C908C54386ABD2D97F'
# yandex_site_verification      : ''
# alexa_verify_id               : ''

favicon-32x32                        : 'favicon-32x32.png'
touch-icon-192x192                   : 'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed : 'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed : 'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed : 'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed : 'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed : 'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed   : 'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed   : 'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed         : 'apple-touch-icon-precomposed.png'
msapplication_tileimage              : 'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor              : '#fabb00'

og_image                             : 'http://images.phlow.de/phlow/phlow_de-logo-512x.png'
og_locale                            : 'es_CL'
og_type                              : 'website'

#  Open _data/socialmedia.yml to adjust the left and right topbar navigation

socialmedia:
    twitter   : jvrenaca
    facebook  : juntadevecinosrenaca
    instagram : jvrenaca

# used in _includes/comments

# disqus_shortname: 

sass:
    sass_dir : _sass
    style    : :compressed

# used in _includes/footer_scripts

# google_analytics_tracking_id:

#  tawk.to is a free live chat app that lets you monitor and chat
#  with visitors on your website or from a free customizable page
#
#  To load the script add tawkto: true in front matter of each page
#
# used in _includes/footer_scripts

# tawkto_embed_uri:

#  Asciidoctor is a fast text processor and publishing toolchain for converting
#  AsciiDoc content to HTML5, DocBook 5 (or 4.5) and other formats.
#
#  https://github.com/asciidoctor/jekyll-asciidoc
#  https://github.com/asciidoctor
asciidoctor-enabled: false
asciidoctor:
  description: 
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font
