# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'NOSOTROS',  url: 'nosotros'}
- {name: 'NUESTRA ZONA', url: 'ubicacion'}
- {name: 'NOTICIAS',       url: 'noticias'}
- {name: 'COMISIONES',      url: 'comisiones'}
- {name: 'BOLSA DE TRABAJO',              url: 'bolsadetrabajo'}
- {name: 'CERTIFICADOS DE RESIDENCIA',            url: 'certificados'}
- {name: 'CONTACTENOS',            url: 'contacto'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/jvrenaca'}
- {icon: 'facebook', link:   'https://www.facebook.com/juntadevecinosrenaca'}
- {icon: 'instagram', link:  'https://instagram.com/jvrenaca'}
- {icon: 'envelope', link:   'mailto:jjvv@renacacosta.org'}

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Comparte!'

related_posts: 'Tambien te podría interesar...'

post_date_prefix: ''
